apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-data-pv
  labels:
    app: storage-service
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/stolen-bike-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data-pvc
  namespace: stolen-bike
  labels:
    app: storage-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: storage-data-pv
